dbt_multi_env:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET_DEV') }}"
      fixed_retries: 1
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE_DEV') }}"
      location: asia-northeast1
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_GOOGLE_PROJECT_DEV') }}"
      threads: 10
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET_PROD') }}"
      fixed_retries: 1
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE_PROD') }}"
      location: asia-northeast1
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_GOOGLE_PROJECT_PROD') }}"
      threads: 10
      timeout_seconds: 300
      type: bigquery